[build]
pattern_preload = "<link rel=\"preload\" href=\"/popup_bg.wasm\" as=\"fetch\" type=\"application/wasm\" crossorigin=\"\"><link rel=\"modulepreload\" href=\"/popup.js\">"
pattern_script = "<script type=\"module\" src=\"/init_popup.js\"></script>"
filehash = false


[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-i", "./popup/assets/styles.css", "-o", "./popup/assets/popup_styles.css"]

[[hooks]]
stage = "post_build"
command = "rm"
command_arguments = ["./popup/assets/popup_styles.css"]

[tools]
wasm-bindgen = {version="0.2.89"}
tailwindcss="3.3.6"

