[package]
name = "content"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "^0.2.87"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1.6"
reqwest-wasm = "0.11.16"
serde = { version = "1.0.164", features = ["derive"] }
browser-rpass = { path = "../"}
serde_json = "1.0.96"
yew = {workspace=true, features=["ssr"]}
log = {workspace=true}
fern ={workspace =true}
gloo={workspace = true}
gloo-utils = { workspace=true, features = ["serde"] }
cfg-if = "0.1"

console_log = {workspace=true, features = ["color"],optional = true}
# material-yew = "0.3.0"




[dependencies.web-sys]
workspace = true
features = [
    "console",
    "Window",
	"Document",
	"HtmlElement",
	"HtmlDocument",
	"HtmlInputElement",
	"HtmlTextAreaElement",
	"Navigator",
	"Clipboard",
	"CssStyleDeclaration",
	"HtmlStyleElement",
	"HtmlCollection",
	"HtmlDataListElement",
	"HtmlOptionElement","DomRect",
]
[features]
default = ["console_log"]
