[package]
name = "native-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.96"
serde-wasm-bindgen = "^0.5.0"
gloo = "0.8.0"
gloo-utils = { version = "^0.1.2", features = ["serde"] }
wasm-bindgen = "0.2.87"
rand = "0.8.4"
getrandom={ version = "0.2.3", features = ["js"] }
typetag = "0.2"
enum_dispatch="0.3.12"
wasm-bindgen-futures = "0.4"
js-sys = "^0.3"
console_error_panic_hook = "0.1.6"
reqwest-wasm = "0.11.16"
lazy_static = "1.4.0"
rpass={ path = "../.." }
browser-rpass={ path = "../"}
hex = "0.4.3"
strum = "0.18.0"
strum_macros = "0.18.0"
git2 = "0.17.1"
locale_config = "0.3.0"
[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Window",
	"Document",
	"HtmlElement",
	"HtmlDocument",
	"HtmlInputElement",
	"HtmlTextAreaElement",
	"Navigator",
	"Clipboard",
]
[dependencies.config]
version = "0.11.0"
default-features = false
features = ["toml"]
[dev-dependencies]
tempfile = "3.5.0"
flate2 = "1.0.26"
tar = "0.4.38"
criterion = "0.4.0"
