[package]
name = "popup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "^0.2.87"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1.6"
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.96"
yew = { version = "0.20", features = ["csr"] }
chrono = { version = "0.4.24", features = ["serde"] }
gloo = "0.8.0"
gloo-utils = { version = "0.1", features = ["serde"] }
reqwasm = "0.5.0"
validator = { version = "0.16.0", features = ["derive"] }
yew-router = "^0.17.0"
yewdux = "0.9"
serde-wasm-bindgen = "^0.5.0"
browser-rpass = { path = "../"}
rand = "0.8.4"
getrandom={ version = "0.2.3", features = ["js"] }
typetag = "0.2"
lazy_static = "1.4.0"


[profile.release]
debug = true

[dependencies.web-sys]
version = "^0.3"
features = [
    "console",
    "Window",
	"Document",
	"HtmlElement",
	"HtmlDocument",
	"HtmlInputElement",
	"HtmlTextAreaElement",
	"Navigator",
	"Clipboard",
]
